spring:
  application:
    name: microservice-api-gateway
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
zuul:
  ignored-services: microservice-provider-user                        # \u9700\u8981\u5FFD\u89C6\u7684\u670D\u52A1(\u914D\u7F6E\u540E\u5C06\u4E0D\u4F1A\u88AB\u8DEF\u7531)
  routes:
    movie:                                                            # \u53EF\u4EE5\u968F\u4FBF\u5199\uFF0C\u5728zuul\u4E0A\u9762\u552F\u4E00\u5373\u53EF\uFF1B\u5F53\u8FD9\u91CC\u7684\u503C = service-id\u65F6\uFF0Cservice-id\u53EF\u4EE5\u4E0D\u5199\u3002
      path: /movie/**                                                 # \u60F3\u8981\u6620\u5C04\u5230\u7684\u8DEF\u5F84
      service-id: microservice-consumer-movie-ribbon-with-hystrix     # Eureka\u4E2D\u7684serviceId

